# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
