# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20170419_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='id',
        ),
        migrations.AddField(
            model_name='information',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
