# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_auto_20170419_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
